apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlpv
spec:
  storageClassName: mysqlstorageclass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/u01/data"